"""add chat analytics fields

Revision ID: 177a977f05b2
Revises: 7f90667817ec
Create Date: 2026-08-20 10:03:48.941920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '177a977f05b2'
down_revision: Union[str, Sequence[str], None] = '7f90667817ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('status', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('confidence', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('response_time_ms', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('returned_article_ids', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'returned_article_ids')
    op.drop_column('chat_messages', 'response_time_ms')
    op.drop_column('chat_messages', 'confidence')
    op.drop_column('chat_messages', 'status')
    # ### end Alembic commands ###
