"""add chat analytics fields

Revision ID: 7f90667817ec
Revises: bd3a1355849e
Create Date: 2026-08-20 10:02:40.606839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f90667817ec'
down_revision: Union[str, Sequence[str], None] = 'bd3a1355849e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'audit_logs', 'users', ['actor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    # ### end Alembic commands ###
